spring:
  profiles:
    active: jdbc
---
spring:
  config:
    activate:
      on-profile: file

repository:
  file:
    voucher: "src/main/resources/voucher.csv"
    blacklist: "src/main/resources/customer_blacklist.csv"
---
spring:
  config:
    activate:
      on-profile: jdbc

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/voucher_management?characterEncoding=UTF-8
    username: user
    password: programmers1234
---