spring:
  profiles:
    active: jdbc
---
spring:
  config:
    activate:
      on-profile: file

repository:
  file:
    voucher: "src/main/resources/voucher.csv"
    blacklist: "src/main/resources/customer_blacklist.csv"
---
spring:
  config:
    activate:
      on-profile: jdbc

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
---